### ISSUE TITLE
[Bug] 검색 결과가 없을 때, 검색 입력 란에 클릭 시 검색 결과 이미지와 검색바가 겹치는 현상

### ISSUE THREAD

**Issue by shinpanda** [SobiSa-Expense-Hunter/SobiSa#143]
버그가 무엇인지에 대한 명확하고 간결한 설명입니다.

**스크린샷**
![image](https://github.com/SobiSa-Expense-Hunter/SobiSa/assets/30384031/4c0a0dcc-cb81-4f99-86e3-360583ac3598)

**Comment by Seo0H** [comment]
z-index 수정 후, not found 상태에서 스크롤 시 search input이 header 상단으로 보여지는 버그 발생
header의 z-index가 수정되어야 할 것으로 보임

![2023-06-14 16;03;50](https://github.com/SobiSa-Expense-Hunter/SobiSa/assets/108770949/3fb0c725-9e71-4f56-96ca-d4905598c332)
