### ISSUE TITLE
[Bug] 첫 화면에서 검색창 포커스 시, 로고는 고정된 반면, 본문은 위로 밀리면서 모스 부호처럼 보임

### ISSUE THREAD

**Issue by shinpanda** [SobiSa-Expense-Hunter/SobiSa#144]
버그가 무엇인지에 대한 명확하고 간결한 설명입니다.
**스크린샷**
해당되는 경우 문제를 설명하는 데 도움이 되는 스크린샷을 추가합니다.
![image](https://github.com/SobiSa-Expense-Hunter/SobiSa/assets/30384031/cbaf245d-4de2-4070-9188-b3d92e215a2e)

**추가 컨텍스트**
- 해당 로고의 위에 margin 부분으로 여백을 주면서, 본문 내용이 상단에 보이는 현상을 확인
- 아래 키보드로 밀려진 본문은 스크롤이 생기지 않아, 사용자가 어떤 내용인지 혼란스러움
![KakaoTalk_Image_2023-06-09-17-11-21](https://github.com/SobiSa-Expense-Hunter/SobiSa/assets/30384031/1c3695b3-1688-4ae8-adee-420e9928065a)

**Comment by Seo0H** [comment]
제가 이 부분 수정한거 올려볼게요! header 의 heigth랑 top 위치를 -1로 해서 해결했어요.
