### ISSUE TITLE
[Feature] 인디케이터 하단 고정

### ISSUE THREAD

**Issue by shinpanda** [SobiSa-Expense-Hunter/SobiSa#72]
**기능 요청이 문제와 관련이 있습니까? 설명해 주세요.**
현재 각 페이지 이동 시 인디케이터가 본문 높이에 따라 표시되는 부분이 달라지고 있습니다.

**원하는 솔루션 설명**
레이아웃에 인디케이터 컴포넌트를 추가(인디케이터 푸터 개념으로 생각하여 구현한다면 되지 않을까 싶습니다)

**고려한 대안 설명**
인디케이터 컴포넌트에서 각페이지 주소(useRouter)를 확인해 그 페이지에 따라 이미지가 보여짐

**Comment by Seo0H** [comment]
이 방안이 좋을 것 같긴 하네요! AppLayout에 해당 인디케이터 컴포넌트를 말씀하신대로 푸터처럼 구현하면 될것같아요.
혹시 해당 부분 작업중이실까요?

**Comment by shinpanda** [comment]
아니요 이슈만 올려두고 아직 작업은 진행하지 않았습니당 ㅎㅎ
