### ISSUE TITLE
husky 적용 되지 않는 오류

### ISSUE THREAD

**Issue by Ryong-E** [SobiSa-Expense-Hunter/SobiSa#9]
window에서 설정 후 mac에서 실행 시 권한을 잃는거같습니다
<img width="762" alt="Screen Shot 2023-05-02 at 19 51 43" src="https://user-images.githubusercontent.com/96985256/235647362-726e2453-11d1-4587-bada-4139e41abb3d.png">

**Comment by Ryong-E** [comment]
chmod ug+x .husky/*
권한 설정으로 오류 해결

**Comment by Seo0H** [comment]
확인했습니다! 해결되신것 같으니 이슈는 닫도록 하겠습니다.
